# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: elixir.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='elixir.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x65lixir.proto\x1a google/protobuf/descriptor.proto\"\x0f\n\rElixirOptions:F\n\x0e\x65lixir_fileopt\x12\x1c.google.protobuf.FileOptions\x18\xc1\xc6\x04 \x01(\x0b\x32\x0e.ElixirOptions:H\n\relixir_msgopt\x12\x1f.google.protobuf.MessageOptions\x18\xc1\xc6\x04 \x01(\x0b\x32\x0e.ElixirOptions:F\n\x0e\x65lixir_enumopt\x12\x1c.google.protobuf.EnumOptions\x18\xc1\xc6\x04 \x01(\x0b\x32\x0e.ElixirOptions:?\n\x06\x65lixir\x12\x1d.google.protobuf.FieldOptions\x18\xc1\xc6\x04 \x01(\x0b\x32\x0e.ElixirOptionsB\x1a\n\x18\x66i.mod.protoc.gen.elixir')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


ELIXIR_FILEOPT_FIELD_NUMBER = 74561
elixir_fileopt = _descriptor.FieldDescriptor(
  name='elixir_fileopt', full_name='elixir_fileopt', index=0,
  number=74561, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
ELIXIR_MSGOPT_FIELD_NUMBER = 74561
elixir_msgopt = _descriptor.FieldDescriptor(
  name='elixir_msgopt', full_name='elixir_msgopt', index=1,
  number=74561, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
ELIXIR_ENUMOPT_FIELD_NUMBER = 74561
elixir_enumopt = _descriptor.FieldDescriptor(
  name='elixir_enumopt', full_name='elixir_enumopt', index=2,
  number=74561, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
ELIXIR_FIELD_NUMBER = 74561
elixir = _descriptor.FieldDescriptor(
  name='elixir', full_name='elixir', index=3,
  number=74561, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_ELIXIROPTIONS = _descriptor.Descriptor(
  name='ElixirOptions',
  full_name='ElixirOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['ElixirOptions'] = _ELIXIROPTIONS
DESCRIPTOR.extensions_by_name['elixir_fileopt'] = elixir_fileopt
DESCRIPTOR.extensions_by_name['elixir_msgopt'] = elixir_msgopt
DESCRIPTOR.extensions_by_name['elixir_enumopt'] = elixir_enumopt
DESCRIPTOR.extensions_by_name['elixir'] = elixir

ElixirOptions = _reflection.GeneratedProtocolMessageType('ElixirOptions', (_message.Message,), dict(
  DESCRIPTOR = _ELIXIROPTIONS,
  __module__ = 'elixir_pb2'
  # @@protoc_insertion_point(class_scope:ElixirOptions)
  ))
_sym_db.RegisterMessage(ElixirOptions)

elixir_fileopt.message_type = _ELIXIROPTIONS
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(elixir_fileopt)
elixir_msgopt.message_type = _ELIXIROPTIONS
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(elixir_msgopt)
elixir_enumopt.message_type = _ELIXIROPTIONS
google_dot_protobuf_dot_descriptor__pb2.EnumOptions.RegisterExtension(elixir_enumopt)
elixir.message_type = _ELIXIROPTIONS
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(elixir)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030fi.mod.protoc.gen.elixir'))
# @@protoc_insertion_point(module_scope)
