# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: another.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='another.proto',
  package='Another',
  syntax='proto3',
  serialized_pb=_b('\n\ranother.proto\x12\x07\x41nother\"\x1b\n\nAnotherMsg\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ANOTHERMSG = _descriptor.Descriptor(
  name='AnotherMsg',
  full_name='Another.AnotherMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Another.AnotherMsg.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['AnotherMsg'] = _ANOTHERMSG

AnotherMsg = _reflection.GeneratedProtocolMessageType('AnotherMsg', (_message.Message,), dict(
  DESCRIPTOR = _ANOTHERMSG,
  __module__ = 'another_pb2'
  # @@protoc_insertion_point(class_scope:Another.AnotherMsg)
  ))
_sym_db.RegisterMessage(AnotherMsg)


# @@protoc_insertion_point(module_scope)
