# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: import.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='import.proto',
  package='Imported',
  syntax='proto3',
  serialized_pb=_b('\n\x0cimport.proto\x12\x08Imported\"?\n\x0bMsgImported\x12\x17\n\x0foptional_string\x18\x01 \x01(\t\x12\x17\n\x0frepeated_string\x18\x02 \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MSGIMPORTED = _descriptor.Descriptor(
  name='MsgImported',
  full_name='Imported.MsgImported',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='optional_string', full_name='Imported.MsgImported.optional_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeated_string', full_name='Imported.MsgImported.repeated_string', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['MsgImported'] = _MSGIMPORTED

MsgImported = _reflection.GeneratedProtocolMessageType('MsgImported', (_message.Message,), dict(
  DESCRIPTOR = _MSGIMPORTED,
  __module__ = 'import_pb2'
  # @@protoc_insertion_point(class_scope:Imported.MsgImported)
  ))
_sym_db.RegisterMessage(MsgImported)


# @@protoc_insertion_point(module_scope)
