# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: import.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='import.proto',
  package='Import',
  syntax='proto3',
  serialized_pb=_b('\n\x0cimport.proto\x12\x06Import\"\x1c\n\x0bImportedMsg\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMPORTEDMSG = _descriptor.Descriptor(
  name='ImportedMsg',
  full_name='Import.ImportedMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Import.ImportedMsg.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['ImportedMsg'] = _IMPORTEDMSG

ImportedMsg = _reflection.GeneratedProtocolMessageType('ImportedMsg', (_message.Message,), dict(
  DESCRIPTOR = _IMPORTEDMSG,
  __module__ = 'import_pb2'
  # @@protoc_insertion_point(class_scope:Import.ImportedMsg)
  ))
_sym_db.RegisterMessage(ImportedMsg)


# @@protoc_insertion_point(module_scope)
